[package]
name = "jarvis-tiling"
version.workspace = true
edition.workspace = true

[dependencies]
jarvis-common = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
